name: AelfChat
main: com.alf.chat.AlfChat
version: 0.1
authors: [Eteocles]
description: Chat customization- Channels, Filtering, etc.
depend: []
softdepend: []
commands:
  chat:
    description: ChilldyChat commands
    usage: /<command>
  ch:
    aliases: ['channel', 'channels']
    description: Channel commands
    usage: /<command>
  mych:
    aliases: ['mychannels']
    description: List player's current channels
    usage: /<command>
permissions:
  alfchat.*:
    description: Gives access to administration commands for AlfChat
    children:
      alfchat.channel.guest: true
      alfchat.channel.default: true
      alfchat.channel.mod: true
      alfchat.channel.admin: true
      alfchat.filter.bypass: true