leveling:
    exp-curve: 1.0
    max-exp: 100000
    max-level: 50
    pad-max-level: true
    exp-loss: 0.10
    pvp-exp-loss: 1.0
    max-party-size: 6
    party-exp-bonus: 1.0
    level-loss: false
    mastery-loss: false
    spawner-checks: true
    spawner-exp-mult: .3
    reset-on-death: false
    pvp-range: 50
    min-pvp-level: 1
    pvp-exp-range: 10
    pvp-max-exp-range: 40
    dump-exp-file: true
classes:
    swap-cost: 5000
    old-swap-cost: 0
    prof-swap-cost: 1000
    prof-swap-pow: 3.0
    old-prof-swap-cost: 0
    master-swap-free: true
    first-swap-free: true
    use-prefix: true
    reset-exp-on-change: true
    reset-master-on-change: false
    reset-prof-master-on-change: false
    reset-prof-on-pri-change: false
properties:
    storage-type: yml
    economy: true
    debug: false
    enchant-exp-mult: 3
    global-cooldown: 500 #milli-seconds
    block-tracking-duration: 900000
    max-tracked-blocks: 2000
    food-heal-percent: .05 #total percentage of health regained when full
    slow-while-casting: true
    combat-time: 10000 #milli-seconds
    mysql_username: user
    mysql_password: pass
    mysql_database: dbname
mana:
    interval: 5
    percent: 5
bed:
    enabled: true
    interval: 15
    percent: 5
hats:
    level: 1
    enabled: true
bonus:
    expiration: 3
    exp: 1.25
    message: Bonus experience time enabled!