name: AelfCore
main: com.alf.AlfCore
version: 0.0
authors: [Eteocles | DThielke, Sleaker, Kainzo]
depend: [ Vault ]
commands:
  alf:
    aliases: ['aelf']
    description: AelfCore commands
    usage: /<command>
  skill:
    aliases: ['hskill']
    description: AelfCore command
    usage: /<command> <skill>
  bind:
    description: Bind skill command
    usage: /<command> <skill>
  party:
    aliases: ['pc', 'p']
    description: Party command
    usage: /<command> <args>
  mana:
    description: energy command
    usage: /<command> 
  shush:
    aliases: ['stfu', 'quiet']
    description: Toggle Aelf output
    usage: /<command>
  pet:
    description: Pet commands
    usage: /<command> <args>
permissions:
  alfcore.admin.*:
    description: Gives access to administration commands for AlfCore
    children:
      